#' Neuropsychological Test Scales
#'
#' This file contains character vectors of neuropsychological test scale names,
#' categorized by cognitive domain. These are used by the
#' `get_neuropsych_scales` function and for defining default scales for
#' various domains in the `create_neuropsych_domain` function.

#' @name scales_iq
#' @docType data
#' @title IQ and General Cognitive Ability Scales
#' @description A character vector of scale names related to intelligence quotient (IQ) and general cognitive abilities.
#' @keywords data
scales_iq <- c(
  "Auditory Working Memory (AWMI)",
  "Cognitive Proficiency (CPI)",
  "Crystallized Knowledge",
  "Fluid Reasoning (FRI)",
  "Fluid Reasoning",
  "Full Scale (FSIQ)",
  "Full Scale IQ (FSIQ)",
  "General Ability (GAI)",
  "General Ability",
  "General Intelligence",
  "Global Neurocognitive Index (G)",
  "NAB Attention Index",
  "NAB Executive Functions Index",
  "NAB Language Index",
  "NAB Memory Index",
  "NAB Spatial Index",
  "NAB Total Index",
  "Nonverbal (NVI)",
  "Perceptual Reasoning (PRI)",
  "Perceptual Reasoning",
  "Processing Speed (PSI)",
  "Processing Speed",
  "RBANS Total Index",
  "Test of Premorbid Functioning",
  "TOPF Standard Score",
  "Total NAB Index (T-NAB)",
  "Verbal Comprehension (VCI)",
  "Verbal Comprehension",
  "Visual Perception/Construction",
  "Visual Spatial (VSI)",
  "Vocabulary Acquisition (VAI)",
  "Word Reading",
  "Working Memory (WMI)",
  "Working Memory",
  "Attention Index (ATT)",
  "Language Index (LAN)",
  "Spatial Index (SPT)",
  "Memory Index (MEM)",
  "Executive Functions Index (EXE)"
)

#' @name scales_memory
#' @docType data
#' @title Memory Scales
#' @description A character vector of scale names related to memory functions, including recall, recognition, and learning, from various tests like CVLT, NAB, etc.
#' @keywords data
scales_memory <- c(
  # cvltc
  "Trial 1 Free Recall Total Correct",
  "Trial 5 Free Recall Total Correct",
  "Trials 1-5 Free Recall Total Correct",
  "List B Free Recall Total Correct",
  "Short Delay Free Recall Total Correct",
  "Short Delay Cued Recall Total Correct",
  "Long Delay Free Recall Total Correct",
  "Long Delay Cued Recall Total Correct",
  "Long Delay Yes/No Recognition Hits",
  "Long Delay Yes/No Recognition False Positives",
  "Free Recall Intrusions",
  "Cued-Recall Intrusions",
  "Total Intrusions",
  "Total Repetitions",
  "Trials 1-5 Semantic Clustering Ratio",
  "Trials 1-5 Serial Clustering Ratio",
  "Trials 1-5 % Recall Primacy",
  "Trials 1-5 % Recall Middle",
  "Trials 1-5 % Recall Recency",
  "Trails 1-5 Learning Slope",
  "Trails 1-5 Percent Recall Consistency",
  "Long Delay Recognition Discriminability",
  "Long Delay Recognition Response Bias",
  # cvlt3
  "Trial 1 Correct",
  "Trial 2 Correct",
  "Trial 3 Correct",
  "Trial 4 Correct",
  "Trial 5 Correct",
  "Trials 1-5 Correct",
  "List B Correct",
  "Short Delay Free Recall Correct",
  "Short Delay Cued Recall Correct",
  "Long Delay Free Recall Correct",
  "Long Delay Cued Recall Correct",
  "Total Hits",
  "Total False Positives",
  "Recognition Discriminability (d')",
  "Total Intrusions",
  "Total Repetitions",
  "CVLT-3 Forced-Choice Recognition Hits",
  # cvlt3 brief
  "Trial 1 Correct",
  "Trial 2 Correct",
  "Trial 3 Correct",
  "Trial 4 Correct",
  "Trials 1-4 Correct",
  "Short Delay Free Recall Correct",
  "Short Delay Cued Recall Correct",
  "Long Delay Free Recall Correct",
  "Long Delay Cued Recall Correct",
  "Total Hits",
  "Total False Positives",
  "Recognition Discriminability (d')",
  "Total Intrusions",
  "Total Repetitions",
  "CVLT-3 Forced-Choice Recognition Hits",
  # nabs
  "NAB Memory Index",
  "Shape Learning Immediate Recognition",
  "Shape Learning Delayed Recognition",
  "Shape Learning Percent Retention",
  "Story Learning Immediate Recall",
  "Story Learning Delayed Recall",
  "Story Learning Percent Retention",
  # NAB
  "Memory Index (MEM)",
  "List Learning List A Trial 1 Immediate Recall",
  "List Learning List A Trial 2 Immediate Recall",
  "List Learning List A Trial 3 Immediate Recall",
  "List Learning List A Immediate Recall",
  "List Learning List B Immediate Recall",
  "List Learning List A Short Delayed Recall",
  "List Learning List A Long Delayed Recall",
  "List Learning List A Percent Retention",
  "List Learning List A Long Delayed Forced-Choice Recognition",
  "List Learning List A Long Delayed Forced-Choice Recognition False Alarms",
  "List Learning List A Discriminability Index",
  "List Learning List A Recall vs. Recognition Index",
  "List Learning Semantic Clusters",
  "List Learning Perseverations",
  "List Learning Intrusions",
  "Shape Learning Trial 1 Immediate Recognition",
  "Shape Learning Trial 2 Immediate Recognition",
  "Shape Learning Trial 3 Immediate Recognition",
  "Shape Learning Immediate Recognition",
  "Shape Learning Delayed Recognition",
  "Shape Learning Percent Retention",
  "Shape Learning Delayed Forced-Choice Recognition",
  "Shape Learning Delayed Forced-Choice Recognition False Alarms",
  "Shape Learning Discriminability Index",
  "Story Learning Trial 1 Phrase Unit Immediate Recall",
  "Story Learning Trial 2 Phrase Unit Immediate Recall",
  "Story Learning Phrase Unit Immediate Recall",
  "Story Learning Thematic Unit Immediate Recall",
  "Story Learning Trial 1 Thematic Unit Immediate Recall",
  "Story Learning Trial 2 Thematic Unit Immediate Recall",
  "Story Learning Phrase Unit Delayed Recall",
  "Story Learning Thematic Unit Delayed Recall",
  "Story Learning Phrase Unit Percent Retention",
  "Figure Drawing Immediate Recall",
  "Figure Drawing Percent Retention",
)
